name: Lint GitHub Actions workflows
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    uses: devops-actions/.github/.github/workflows/actionlint.yml@8d8663c88ecbf1ec0da06c0e830055512a6b3890 # main
    permissions:
      contents: read
      pull-requests: write