name: Lint GitHub Actions workflows
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    uses: devops-actions/.github/.github/workflows/actionlint.yml@a634e5b033926a6683519b3ffc7b556312ca7e00 # main
    permissions:
      contents: read
      pull-requests: write