name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@686cfb7424be0c32c8fe4e9e335f4500c5e9978c # main
    permissions:
      contents: read