name: Lint GitHub Actions workflows
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    uses: devops-actions/.github/.github/workflows/actionlint.yml@78ae1648b575b039d174b55ba1f5aaccab81b458 # main
    permissions:
      contents: read
      pull-requests: write